version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_cinema
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cinema_php
      MYSQL_USER: user
      MYSQL_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cinema
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_cinema
    restart: always
    volumes:
      - ./project:/var/www/html
    ports:
      - "82:80"

volumes:
  mysql_data:
